### PR TITLE
Replace deprecated onBackPressed with onBackPressedDispatcher callback

### LINKED ISSUE #195: IssueActivity onBackPressed missing super call
From pull request action build output

IssueActivity.java:273: Error: Overriding method should call super.onBackPressed [MissingSuperCall]
      public void onBackPressed() {
                  ~~~~~~~~~~~~~
  
     Explanation for issues of type "MissingSuperCall":
     Some methods, such as View#onDetachedFromWindow, require that you also call
     the super implementation as part of your method.

### PR DESCRIPTION
**Pull request by brericha**
Closes #195

### CODE REVIEW

File: 5calls/app/src/main/java/org/a5calls/android/a5calls/controller/TutorialActivity.java [hunk 1]
```diff
@@ -40,22 +42,30 @@ protected void onCreate(@Nullable Bundle savedInstanceState) {
...
+        getOnBackPressedDispatcher().addCallback(this, new OnBackPressedCallback(true) {
+            @Override
+            public void handleOnBackPressed() {
+                if (binding.viewPager.getCurrentItem() == 0) {
+                    // If the user is currently looking at the first step, allow the system to handle the
+                    // Back button. Call finish() on this activity and pop the back stack.
+                    finish();
+                } else {
+                    // Otherwise, select the previous step.
+                    binding.viewPager.setCurrentItem(binding.viewPager.getCurrentItem() - 1);
```
Comment (dektar) [inline 5calls/app/src/main/java/org/a5calls/android/a5calls/controller/TutorialActivity.java:54]: call onPreviousPagePressed instead of duplicating that logic?

**Review by dektar — COMMENTED** [review]
Looks good, one suggestion. Speaking of the PR template, how did you test this? Did you test all the updated activities' back handling manually?

**Comment by brericha** [comment]
Yes, I manually "pressed" (swipe gesture) back on each page that had been changed

**Review by dektar — APPROVED** [review]
