### PR TITLE
Fixed NPE when search didn't match anything in placeholder issue

### LINKED ISSUE #301: NullPointerException in filterIssuesBySearchText in latest version
Exception java.lang.NullPointerException: Attempt to get length of null array
  at org.a5calls.android.a5calls.adapter.IssuesAdapter.filterIssuesBySearchText (IssuesAdapter.java:214)
  at org.a5calls.android.a5calls.adapter.IssuesAdapter.setFilterAndSearch (IssuesAdapter.java:146)
  at org.a5calls.android.a5calls.controller.MainActivity.setSearchText (MainActivity.java:844)
  at org.a5calls.android.a5calls.controller.MainActivity.onIssueSearchSet (MainActivity.java:822)
  at org.a5calls.android.a5calls.controller.SearchIssuesDialog$1.onClick (SearchIssuesDialog.java:68)
  at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage (AlertController.java:167)
  at android.os.Handler.dispatchMessageImpl (Handler.java:142)
  at android.os.Handler.dispatchMessage (Handler.java:125)
  at android.os.Looper.loopOnce (Looper.java:269)
  at android.os.Looper.loop (Looper.java:367)
  at android.app.ActivityThread.main (ActivityThread.java:9333)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:566)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:929)

### PR DESCRIPTION
**Pull request by scottpeterson**
Also changed functionality so that upon searching, any set Filter gets unset

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization

## Related Issues

- Related Issue #
- Closes #301

## Were the changes tested?

- [ ] Yes, automated tests in _please name test methods or files_
- [ ] Yes, manually tested: _please provide steps performed to test changes_
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

### CODE REVIEW

File: 5calls/app/src/main/java/org/a5calls/android/a5calls/adapter/IssuesAdapter.java [hunk 1]
```diff
@@ -125,19 +122,9 @@ public void setBookmarkedIds(Set<String> ids) {
...
-        }
-    }
-
     public void setFilterAndSearch(String filterText, String searchText) {
-        mLastFilterText = filterText;
-        mLastSearchText = searchText;
         if (mErrorType == ERROR_SEARCH_NO_MATCH || mErrorType == ERROR_BOOKMARKS_EMPTY) {
-            // If we previously had a search or bookmarks error, reset it: this is a new
-            // filter or search.
+            // If we previously had a search or bookmarks error, reset it: this is a new filter or search.
```
Comment (dektar) [inline 5calls/app/src/main/java/org/a5calls/android/a5calls/adapter/IssuesAdapter.java]: can we keep the line wrapping?

File: 5calls/app/src/main/java/org/a5calls/android/a5calls/adapter/IssuesAdapter.java [hunk 2]
```diff
@@ -224,14 +213,18 @@ public static ArrayList<Issue> filterIssuesBySearchText(String searchText, List<
...
-                if (pattern.matcher(issue.reason).find()) {
+                if (!TextUtils.isEmpty(issue.reason) && pattern.matcher(issue.reason).find()) {
                     tempIssues.add(issue);
                 }
             }
         }
         return tempIssues;
     }
 
+    private static boolean containsIgnoreCase(String text, String lowercaseSearchText) {
```
Comment (dektar) [inline 5calls/app/src/main/java/org/a5calls/android/a5calls/adapter/IssuesAdapter.java]: can lowercaseSearchText be null? I think that would cause a crash. Maybe we can just add a @NotNull annotation to the second param?

File: 5calls/app/src/main/java/org/a5calls/android/a5calls/model/Issue.java [hunk 3]
```diff
@@ -5,10 +5,10 @@
 import android.text.TextUtils;
 
 import java.util.Collections;
-import org.a5calls.android.a5calls.util.StateMapping;
-
 import java.util.List;
 
+import org.a5calls.android.a5calls.util.StateMapping;
```
Comment (dektar) [inline 5calls/app/src/main/java/org/a5calls/android/a5calls/model/Issue.java:8]: do we need this import?

File: 5calls/app/src/test/java/org/a5calls/android/a5calls/adapter/IssuesAdapterTest.java
Comment (dektar) [inline 5calls/app/src/test/java/org/a5calls/android/a5calls/adapter/IssuesAdapterTest.java:556]: why remove this comment? it still seems correct?

File: 5calls/app/src/main/java/org/a5calls/android/a5calls/model/Issue.java (hunk 3 above)
Comment (scottpeterson) [reply 5calls/app/src/main/java/org/a5calls/android/a5calls/model/Issue.java:8]: this was caused by the same auto-formatting that changed the two-line comment into a one-line. 

I'll revert both. 

But this import existed before this PR, it's needed on line 145. This PR just reordered the imports.

**Review by dektar — APPROVED** [review]
